apiVersion: networking..k8s.io/v1
kind: Ingress
metadata:
  name: controller
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          {{- range  $key, $val := .Values.services}}
          {{- if (hasKey $val "publishUrl") }}
          - path: {{ "/api/(.*)" }}
            pathType: Prefix
            backend:
              service:
                name: gateway-service
                port:
                  number: 8080
          - path: {{ "/api/(.*)" }}
            pathType: Prefix
            backend:
              service:
                name: category-service
                port:
                  number: 8060
          - path: {{ "/api/(.*)" }}
            pathType: Prefix
            backend:
              service:
                name: identity-provider
                port:
                  number: 8030
          - path: {{ "/api/(.*)" }}
            pathType: Prefix
            backend:
              service:
                name: kafka-service 
                port:
                  number: 9092
          - path: {{ "/api/(.*)" }}
            pathType: Prefix
            backend:
              service:
                name: namespace-service
                port:
                  number: 8050
          - path: {{ "/api/(.*)" }}
            pathType: Prefix
            backend:
              service:
                name: notes-service
                port:
                  number: 8070
          - path: {{ "/api/(.*)" }}
            pathType: Prefix
            backend:
              service:
                name: statistic-service
                port:
                  number: 8040
          - path: {{ "/api/(.*)" }}
            pathType: Prefix
            backend:
              service:
                name: zookeeper-service
                port:
                  number: 2181
          - path: {{ "/api/(.*)" }}
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 8081
          {{- end}}
          {{- end }}
