apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: services-ingress
  labels:
    app.kubernetes.io/name: services-ingress
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: micro-services
    app.kubernetes.io/managed-by: helm
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: "/api/gateway-service/"
            pathType: Prefix
            backend:
              service:
                name: gateway-service
                port:
                  number: 8080
          - path: "/api/category-service/"
            pathType: Prefix
            backend:
              service:
                name: category-service
                port:
                  number: 8060
          - path: "/api/identity-provider/"
            pathType: Prefix
            backend:
              service:
                name: identity-provider
                port:
                  number: 8030
          - path: "/api/kafka-service/"
            pathType: Prefix
            backend:
              service:
                name: kafka-service
                port:
                  number: 9092
          - path: "/api/namespace-service/"
            pathType: Prefix
            backend:
              service:
                name: namespace-service
                port:
                  number: 8050
          - path: "/api/notes-service/"
            pathType: Prefix
            backend:
              service:
                name: notes-service
                port:
                  number: 8070
          - path: "/api/statistic-service/"
            pathType: Prefix
            backend:
              service:
                name: statistic-service
                port:
                  number: 8040
          - path: "/api/zookeeper-service/"
            pathType: Prefix
            backend:
              service:
                name: zookeeper-service
                port:
                  number: 2181
