name: Build Project
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push services
        run: |
          docker build --no-cache -t andreevaa/postgres gateway_service && docker push andreevaa/postgres:latest
          docker build --no-cache -t andreevaa/pgadmin gateway_service && docker push andreevaa/pgadmin:latest
          docker build --no-cache -t andreevaa/zookeeper gateway_service && docker push andreevaa/zookeeper:latest
          docker build --no-cache -t andreevaa/kafka gateway_service && docker push andreevaa/kafka:latest
          docker build --no-cache -t andreevaa/gateway_service gateway_service && docker push andreevaa/gateway_service:latest
          docker build --no-cache -t andreevaa/category_service category_service && docker push andreevaa/category_service:latest
          docker build --no-cache -t andreevaa/identity_provider identity_provider && docker push andreevaa/identity_provider:latest
          docker build --no-cache -t andreevaa/namespace_service namespace_service && docker push andreevaa/namespace_service:latest
          docker build --no-cache -t andreevaa/notes_service notes_service && docker push andreevaa/notes_service:latest
          docker build --no-cache -t andreevaa/statistic_service statistic_service && docker push andreevaa/statistic_service:latest
          docker build --no-cache -t andreevaa/frontend frontend && docker push andreevaa/frontend:latest
      - name: Deploy
        run: |
          kubectl config set-cluster k8s --server="${{ secrets.SERVER_URL }}" --insecure-skip-tls-verify=true
          kubectl config set-credentials main-admin --token="${{ secrets.SA_TOKEN }}"
          kubectl config set-context default --cluster=k8s --user=main-admin
          kubectl config use-context default

          cd k8s
          helm upgrade services ./services-chart
          sleep 60
      - name: Build images
        timeout-minutes: 10
        run: |
          docker build gateway_service --target tests
          docker build notes_service --target tests
          docker build category_service --target tests
          docker build namespace_service --target tests
          docker build statistic_service --target tests
          docker build identity_provider --target tests
      - name: Run containers
        timeout-minutes: 5
        run: |
          docker compose build
          docker compose up -d
          ./scripts/wait-script.sh
        env:
          WAIT_PORTS: 8080,8070,8060,8050,8040,8030
      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
            collection: v5/postman/collection.json
            environment: v5/postman/environment.json
            delayRequest: 100
            reporters: '[ "cli" ]'
      - name: Stop containers
        if: always()
        continue-on-error: true
        run: docker compose down -v