name: Build Project
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push services
        run: |
          docker build --no-cache -t andreevaa/gateway_service gateway_service && docker push gateway_service:latest
          docker build --no-cache -t andreevaa/category_service category_service && docker push category_service:latest
          docker build --no-cache -t andreevaa/identity_provider identity_provider && docker push identity_provider:latest
          docker build --no-cache -t andreevaa/namespace_service namespace_service && docker push namespace_service:latest
          docker build --no-cache -t andreevaa/notes_service notes_service && docker push notes_service:latest
          docker build --no-cache -t andreevaa/statistic_service statistic_service && docker push statistic_service:latest
          docker build --no-cache -t andreevaa/frontend frontend && docker push frontend:latest
