name: Build Project
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push services
        run: |
          docker build --no-cache -t gateway_service && docker push gateway_service:latest
          docker build --no-cache -t category_service && docker push category_service:latest
          docker build --no-cache -t identity_provider && docker push identity_provider:latest
          docker build --no-cache -t namespace_service && docker push namespace_service:latest
          docker build --no-cache -t notes_service && docker push notes_service:latest
          docker build --no-cache -t statistic_service && docker push statistic_service:latest
          docker build --no-cache -t frontend && docker push frontend:latest
